global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:8000']
